### ISSUE TITLE
Text overflows info box for MakerBit extension

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#21]
![image](https://user-images.githubusercontent.com/13832091/48331714-d8b89300-e605-11e8-90f6-6bcd19569354.png)

Also, "makerbit" should be "MakerBit".

**Comment by philipphenkel** [comment]
@HyperDuino 

What about 

> The MakerBit connects to a wide variety of sensors, actuators, and other components.

"makerbit" vs "MakerBit": All package names are displayed in lower-case

**Comment by HyperDuino** [comment]
Sounds good

**Comment by philipphenkel** [comment]
@HyperDuino Overflow is fixed. I had to with an even shorter version: "The MakerBit connects to a wide variety of components."
