### ISSUE TITLE
feature request;

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#23]
In addition to "A" and "B" in the motor direction block:

![image](https://user-images.githubusercontent.com/13832091/49324822-53305080-f4ea-11e8-9d47-3f8cd01d1cf2.png)

How about a 3rd option in the pop-up for "both".

This would reduce this code from 4 blocks to 3:

![image](https://user-images.githubusercontent.com/13832091/49324827-6f33f200-f4ea-11e8-9354-10a3fb7987c7.png)

One could also have "both" in the run motor blocks, which would allow the above code to be just 2 blocks instead of 4.

**Comment by philipphenkel** [comment]
That's a great idea! I propose to call the third option "A + B".

> run motor A + B at speed 80

**Comment by HyperDuino** [comment]
Sounds good

**Comment by philipphenkel** [comment]
Implemented in version 0.17.11
