### ISSUE TITLE
Missing locale for mp3command

### ISSUE THREAD

**Issue by MKleinSB** [1010Technologies/pxt-makerbit#25]
I think there should be translated blocks for the mp3command Constants. Good idea or not :-)
You see Philipp, I´m still working on it. 
![mp3command](https://user-images.githubusercontent.com/37311672/52441482-fd4adb00-2b20-11e9-90db-52472f3a8875.png)

**Comment by philipphenkel** [comment]
Thanks for pointing that out! Fixed in https://github.com/1010Technologies/pxt-makerbit-mp3 and will available here with next dependency update.
