### ISSUE TITLE
Implement MP3 folder management

### ISSUE THREAD

**Issue by philipphenkel** [1010Technologies/pxt-makerbit#3]
Allow selection of a MP3 folder and modify playMp3Track so that plays tracks from the active folder only.

Use case: localization of a project where language files are placed in separate folders

![unnamed](https://user-images.githubusercontent.com/828416/42423486-59186156-82fb-11e8-9484-c73145d327fd.png)

**Comment by philipphenkel** [comment]
playMp3Track was removed and in general we should avoid stateful blocks (e.g. which refer to the current folder). Therefore, I recommend to close this request without any additional changes.

**Comment by HyperDuino** [comment]
Agreed. Closed.
