### ISSUE TITLE
Restore "%" to motor block

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#4]
Previously, the motor control block followed the speed variable with "%", but this was removed.  Recommend restoring so that it's clear that the expected number value is 0-100.

Negative values maintain the behavior to move the motor in a reverse direction.

**Comment by philipphenkel** [comment]
The functionality seems to work as expected and the range is reflected in both the documentation and in the UI via a slider.

![bildschirmfoto 2018-07-30 um 21 31 11](https://user-images.githubusercontent.com/828416/43418986-ee0fe310-943f-11e8-96de-4ed17bdf78e8.png)
 
Units (or %) should not be placed after a parameter. The only option is to place them before the value. See Music block "set tempo to (bpm) 120" for an example. We could realize "run motor A at speed (%) 80". Personally, I think the % sign is adding more confusion in this case.

**Comment by HyperDuino** [comment]
Good points.  We will leave the block as it is now.
