### ISSUE TITLE
How to print number with LCD block

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#6]
LCD block can only print strings. How to print a variable which is a number?

**Comment by philipphenkel** [comment]
Please use block showNumberOnLcd, the block below showStringOnLcd.

![bildschirmfoto 2018-08-19 um 21 51 29](https://user-images.githubusercontent.com/828416/44312533-2acc8c80-a3fa-11e8-8e6e-6e9c4b201df7.png)
