### ISSUE TITLE
All LEDs off block

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#7]
It would be useful to have a block that would turn all LEDs 5-16 off for use in the "on start" part of MakerBit programs.

**Comment by philipphenkel** [comment]
@HyperDuino Would like to create some convenient LED blocks? At the moment we don't have any explicit support for the "LED" pins.

**Comment by HyperDuino** [comment]
#8 applies to pins 5-16 which in turn are connected to LEDs.  In particular I would like to be able to turn all 5-16 pins off as part of the Start because it seems that some times even with LED enable false, that various pins are "on".  This isn't "all on" or "all off" for the built-in microbit LED display.
