### ISSUE TITLE
Variable for pin #s

### ISSUE THREAD

**Issue by HyperDuino** [1010Technologies/pxt-makerbit#8]
Let's create some blocks for the basic pin functions that allow variables for the pin #.

![image](https://user-images.githubusercontent.com/13832091/44066666-6025999a-9f26-11e8-85f4-f2630c091c51.png)

**Comment by philipphenkel** [comment]
In MakeCode this could like the following contruction:
![bildschirmfoto 2018-08-25 um 15 40 50](https://user-images.githubusercontent.com/828416/44618794-4c57c900-a87d-11e8-9600-0c8d3b8779b6.png)

Does this meet your requirements?
